Updates
ImageInLib/ImageInLib pull request #47
Opened 2022-09-05 13:07 UTC by KonanAl

resquet 1 : dataType for loading and saving functions

2022-09-13 15:02 UTC, deaspo requested changes
- Only submit changes that have been tested
- Avoid usage of hardcorded values
- Leave untouched functions that you haven't tested
- Test the library and address all warnings, avoid duplicating implementations

2022-09-21 12:26 UTC, KonanAl commented on ImageInLib/ImageInLib/src/noise_generator.h
> +	void addStructuralNoise(dataType **imageDataPtr, int imageHeight, int imageWidth);
I really didn't test functions for adding structural noises (In my second version of the library), so I supposed that they are in they original version. But I see and understand the issues your pointed, I will fix them, thanks.

2022-09-21 12:28 UTC, closed without merging

2022-09-22 07:53 UTC, KonanAl commented on ImageInLib/ImageInLib/include/common_functions.h
> +	} NoiseParameters;
It was not defined in my version of noiseGeneration.h. But, I move it there, now

2022-09-22 08:32 UTC, deaspo commented
Synchronize your master and updates branch before making a pull request to the imageInLib master branch.