Update in GSUBSURF
ImageInLib/ImageInLib pull request #89
Opened 2023-09-06 11:14 UTC by KonanAl

The pull request includes extension of the structure Segment_Parameters in order to check if the initial segment is binary image or not. If it is then we don't modify initial foreground pixels so the initial segment just grow.

2023-09-06 14:53 UTC, JozoUrban requested changes

2023-09-21 06:54 UTC, JozoUrban requested changes

2023-09-21 06:54 UTC, JozoUrban commented on ImageInLib/ImageInLib/src/segmentation3D_subsurf.c
> +#pragma warning(disable:6385)
...Are you going to resolve this comment in separate PR?
IF so, then remove the pragmas please, to see the warnings you want to resolve.

2023-09-21 06:54 UTC, JozoUrban commented on ImageInLib/ImageInLib/src/segmentation3d_gsubsurf.c
> +#pragma warning(disable:6385)
...Are you going to resolve this comment in separate PR?
IF so, then remove the pragmas please, to see the warnings you want to resolve.

2023-09-21 08:24 UTC, KonanAl commented on ImageInLib/ImageInLib/src/segmentation3D_subsurf.c
> +#pragma warning(disable:6385)
Yes, I will do it in new pull request, cause I still need to investigate how to solve the issue differently

2023-09-21 09:47 UTC, JozoUrban approved these changes

2023-09-21 09:48 UTC, merged